server:
  port: 9999

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*,refresh"  # 修改: 添加refresh到include中
  endpoint:
    env:
      post:
        enabled: true
    refresh:  # 添加: refresh端点配置
      post:
        enabled: true  # 添加: 启用refresh端点的POST方法

spring:
  profiles:
    active: git, native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          basedir: target/config
        native:
          search-locations: classpath:/config/broker/{application}
          addLabelLocations: false