apiVersion: v1
kind: Pod
metadata:
  name: test-web-pod
  labels:
    app: test-web
spec:
  containers:
    - name: test-web-container
      image: image-registry.openshift-image-registry.svc:5000/workshop/test-web
      ports:
        - containerPort: 8080
        - containerPort: 9443